resources:
- deployment.yaml
- service.yaml
- ingress.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: var-image
  newName: eu.gcr.io/monadium/monadium
  newTag: f133e54992ce832e0fd1d8865c6ddd9a4b427b88
