resources:
- deployment.yaml
- service.yaml
- ingress.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: var-image
  newName: eu.gcr.io/monadium/monadium
  newTag: 2f170ada0f702b58b556a782348ac9c828bae9ae
