resources:
- deployment.yaml
- horizontal-pod-autoscaler.yaml
- service.yaml
- ingress.yaml
- managed-certificate.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: var-image
  newName: eu.gcr.io/monadium/monadium
  newTag: 69fbdb2c19a1c5f36b0145d83219612861eb50df
