resources:
- deployment.yaml
- horizontal-pod-autoscaler.yaml
- service.yaml
- ingress.yaml
- managed-certificate.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: var-image
  newName: eu.gcr.io/monadium/monadium
  newTag: 481dce65bd1d637dc8b786b7271be2fdf33d126e
