name: CD

on:
  push:
    branches:
      - "main"

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_GKE_CLUSER: monadium-cluster
  GCP_REGION: europe-north1
  K8S_DEPLOYMENT_NAME: ${{ secrets.K8S_DEPLOYMENT_NAME }}

jobs:
  cd:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Auth kubernetes
        run: |-
          gcloud container clusters get-credentials ${{ env.GCP_GKE_CLUSTER }} --region ${{ env.GCP_REGION }}

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          ./kustomize build k8s/base/monadium | kubectl apply -f -
          kubectl rollout status deployment/${{ env.K8S_DEPLOYMENT_NAME }}
          kubectl get services -o wide
